version: '3'
services:
  nginx:
    build:
      context: app/docker/development
      dockerfile: nginx.docker
    volumes:
      - ./app:/app
    depends_on:
      - php-fpm
    ports:
      - 8081:80
  php-fpm:
    build:
      context: app/docker/development
      dockerfile: php-fpm.docker
    volumes:
      - ./app:/app
    depends_on:
      - postgres
  php-cli:
    build:
      context: app/docker/development
      dockerfile: php-cli.docker
    volumes:
      - ./app:/app
      - ./composer:/root/.composer/cache
    depends_on:
      - postgres
  postgres:
    image: postgres:13.3-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    ports:
      - 54321:5432
  # тестовая база
  postgres-test:
    image: postgres:13.3-alpine
    volumes:
      - postgres-test:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app_test
    ports:
      - 54322:5432

volumes:
  composer:
  postgres:
  postgres-test:
